### ISSUE TITLE
generateFingerprint doesn't finish

### ISSUE THREAD

**Issue by vavramovski** [antoinevastel/fp-collect#11]
I am running tests to see what is extracted from Selenium chrome webdriver vs Normal browser.

I am running the following code 
```
<script src="fpCollect.js"></script>
    <script>
        async function test(){
            let fp;
            try {
                fp = await fpCollect.generateFingerprint()
            } catch (e) {
                console.log(e)
            }
            console.log(fp)
        }

        test();
    </script>
```

The code works when I run it in Normal browser, but doesn't work when I run it in Selenium chrome webdriver and it's blocking in this line : 
`fp = await fpCollect.generateFingerprint()`

I was digging a little in the code fpCollect.js code, and as I found out, some of the promises are not resolving and that's why generateFingerprint doesn't finish (but this only happens with selenium chrome driver.

Any help would be appreciated !

**Comment by antoinevastel** [comment]
Hello, sorry, I can't provide any support/update regarding this library because of the nature of my current job.
