### ISSUE TITLE
TypeError: fpcollect.generateFingerprint is not a function

### ISSUE THREAD

**Issue by daishisystems** [antoinevastel/fp-collect#2]
Error is returned when running the following script:

```
var fpcollect = require('fpcollect');
fpcollect.generateFingerprint().then((fingerprint) => {
    console.log(fingerprint);
});
```
=> **TypeError: fpcollect.generateFingerprint is not a function**

**Comment by antoinevastel** [comment]
Since fp-collect script must be run in the browser, you cannot use the require statement.
Instead you need to run: ```npm build ```
This generates a minified version called fpcollect.js in the dist/ directory.
You can then add it to your page using a <script> tag, an collect a fingerprint using the code below:

```
fpcollect.generateFingerprint().then((fingerprint) => {
    console.log(fingerprint);
});
```

**Comment by antoinevastel** [comment]
Hello Ydnar, thanks for posting the issue. I'm not familiar with Vue and I'm currently quite busy with the end of my internship. I can look at it in 2 weeks when I have more time, but feel free to submit a PR if you need to fix it faster.

Antoine

**Comment by ydnar** [comment]
Update: I was able to get it working by importing from `src` directly:

```js
import fpcollect from 'fpcollect/src/fpCollect.js'
import fpscanner from 'fpscanner'

export default async ({ env }, inject) => {
  let fingerprint
  let results
  try {
    fingerprint = await fpcollect.generateFingerprint()
    results = fpscanner.analyseFingerprint(fingerprint)
  } catch (error) {
    console.log('Error:', error)
  }

  for (let result in results) {
    console.log(`${result.name}: ${result.consistent}`)
  }
}
```

(This is a [Nuxt](http://github.com/nuxt/nuxt.js) plugin.)

Good luck with your internship!
