### ISSUE TITLE
Sequentum check breaking IE11

### ISSUE THREAD

**Issue by gil** [antoinevastel/fp-collect#4]
Hi! The check you have here:

https://github.com/antoinevastel/fp-collect/blob/f3a7f568a2af7be4711b65f3cd398cc49f10b1d8/src/fpCollect.js#L349

Is breaking on IE11. For some reason, `toString` is undefined inside `window.external`. So you can probably just check for `&& window.external.toString` before calling... Or even replace everything with something like `('' + window.external).indexOf('Sequentum') > -1`

Cheers

**Comment by antoinevastel** [comment]
Hi, Thanks for posting the issue. I will modify it this week end.

Antoine

**Comment by antoinevastel** [comment]
I pushed a modification. Once again, thanks for having taken the time to post the issue.

Antoine
